import './globals.css'
 

const API = 'https://api-ap-south-1.hygraph.com/v2/clk94bseu1ws701t29jgj1bc0/master'



export const metadata = {
  title: 'JubairSights',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
      
    </html>
  )
}






// export async function getStaticProps() {
//   const { data } = await client.query({
//     query: gql`
//       query {
//         streamss {
//           title
//           slug
//           streamDate
//           coverimage {
//             url
//           }
//           guestname
//         }
//       }
//     `,
//   });

//   const {streamss} = data
//   {console.log(streamss)}

//   return {
//     props: {
//       streamss,
//     },
//   };
// }
